# ============================================================
#  C4 - Configuração
#  Criptografia Aplicada | LSIRC 2025/2026
# ============================================================

# PDF de entrada (com os dados do grupo preenchidos)
pdf.entrada=acordo_grupo.pdf

# PDF de saída (com todas as assinaturas)
pdf.saida=acordo_grupo_assinado.pdf